
TOKEN = "7408170935:AAHmG3SkTTQy-7eRNyOgSoB9vAD1Bl_H2Gc"
pochta = r'C:\Program Files (x86)\Фасады МДФ\Dati_c'
# put = r'\\Sergey\фасады мдф\Dati_c\Заказы23.RSB'
# put_555ss = '//Bhc/a1/mp4/BIMGOR/KLIENTY'
# put_555nc = '//Bhc111/bimgor'
# put_555it = "//BS1000046997/Users/Public/Bimgor"
# put_ss = '//SERGEY/Dati_c/ss/'
# put_nc = '//SERGEY/Dati_c/nc/'
# put_it = '//SERGEY/Dati_c/it/'
put = r'C:\Program Files (x86)\Фасады МДФ\Dati_c\Заказы'
put_ras = r'C:\Program Files (x86)\Фасады МДФ\Dati_c\Расходы.RSB'
put_dat = r'C:\Program Files (x86)\Фасады МДФ\Dati_c\dati\DAT.DB'
put_fasad = r'C:\Program Files (x86)\Фасады МДФ\Dati_c\dati\Fasad.db'
put_ss = 'C:/555/ss/'
put_nc = 'C:/555/nc/'
put_it = 'C:/555/it/'
put_ss_zip = 'C:/555/'
put_nc_zip = 'C:/555/'
put_it_zip = 'C:/555/'
put_555ss = r'C:\VirtualBox\Virtual_share\FasadBG_it\Fasad\bin\Debug\555_ss'
put_555nc = r'C:\VirtualBox\Virtual_share\FasadBG_it\Fasad\bin\Debug\555_nc'
put_555it = r'C:\VirtualBox\Virtual_share\FasadBG_it\Fasad\bin\Debug\555_it'
put_old = '//office/555/old/'

